#!/usr/bin/env python3
"""
Generate and test 1000 diverse questions to verify routing and response quality.
Tests all categories: weather, sports, airports, general knowledge, science, history, etc.
"""

import json
import asyncio
import httpx
import time
from typing import List, Dict, Any
from datetime import datetime

# Service URLs
GATEWAY_URL = "http://192.168.10.167:8000"
ORCHESTRATOR_URL = "http://192.168.10.167:8001"

# Use orchestrator directly to avoid HA conversation logic issues
USE_ORCHESTRATOR_DIRECT = True

# 1000 diverse questions covering all possible query types
QUESTIONS = [
    # WEATHER (50 questions)
    "What's the weather today?",
    "What's the weather in Baltimore?",
    "Will it rain tomorrow?",
    "What's the temperature outside?",
    "Is it going to snow this week?",
    "What's the forecast for this weekend?",
    "What's the weather like in New York?",
    "Is it sunny today?",
    "What's the humidity right now?",
    "What's the wind speed?",
    "Is there a storm coming?",
    "What's the weather forecast for tonight?",
    "How cold is it outside?",
    "What's the heat index?",
    "Is it going to be windy?",
    "What's the chance of rain?",
    "What's the UV index today?",
    "Is it foggy outside?",
    "What's the dew point?",
    "What's the air quality?",
    "When will the rain stop?",
    "What's the weather in Los Angeles?",
    "Is it hotter than yesterday?",
    "What's the feels-like temperature?",
    "Is there a weather advisory?",
    "What's the barometric pressure?",
    "Will there be thunderstorms?",
    "What's the weather in Miami?",
    "Is it cloudy today?",
    "What's the wind direction?",
    "What's the weather in Chicago?",
    "Is it raining right now?",
    "What's the low temperature tonight?",
    "What's the high temperature tomorrow?",
    "Is there a frost warning?",
    "What's the weather in Seattle?",
    "Is it snowing anywhere?",
    "What's the precipitation amount?",
    "What's the weather in Boston?",
    "Is it warmer today?",
    "What's the weather in Denver?",
    "Is there fog this morning?",
    "What's the weather in San Francisco?",
    "Is it going to be clear tonight?",
    "What's the weather in Dallas?",
    "Is the weather nice today?",
    "What's the weather in Atlanta?",
    "Is it humid outside?",
    "What's the weather in Phoenix?",
    "When will the snow start?",

    # SPORTS (50 questions)
    "When do the Ravens play next?",
    "What's the Ravens score?",
    "Did the Orioles win yesterday?",
    "Ravens schedule this week",
    "Who won the Ravens game?",
    "What time is the Ravens game?",
    "How are the Orioles doing?",
    "Ravens vs Bengals score",
    "Did the Ravens win?",
    "Orioles game today",
    "Ravens playoff chances",
    "Who's playing tonight in NFL?",
    "NBA scores today",
    "Did the Lakers win?",
    "What's the score of the Warriors game?",
    "Who won the Super Bowl?",
    "MLB standings",
    "NFL scores this week",
    "Who's leading the NBA?",
    "Did the Yankees win?",
    "What's the Red Sox score?",
    "Who's winning the World Series?",
    "NHL scores today",
    "Did the Capitals win?",
    "What's the Penguins score?",
    "Who won the Stanley Cup?",
    "NBA playoff schedule",
    "Who's the MVP this season?",
    "What's the Cowboys score?",
    "Did the Patriots win?",
    "Who's playing Monday Night Football?",
    "What's the Chiefs score?",
    "Did the 49ers win?",
    "Who won the basketball game?",
    "What's the score of the hockey game?",
    "Did the Dodgers win?",
    "What's the Cubs score?",
    "Who's playing in the playoffs?",
    "What's the Eagles score?",
    "Did the Packers win?",
    "Who won the football game last night?",
    "What's the Seahawks score?",
    "Did the Steelers win?",
    "Who's the best team in football?",
    "What's the Bills score?",
    "Did the Rams win?",
    "Who's playing college football today?",
    "What's the Alabama score?",
    "Did Ohio State win?",
    "Who won March Madness?",

    # AIRPORTS (30 questions)
    "Are there delays at BWI?",
    "BWI flight status",
    "Any delays at Baltimore airport?",
    "Is BWI airport open?",
    "Flight delays at BWI?",
    "Are there cancellations at BWI?",
    "What's the wait time at BWI security?",
    "Is DCA airport delayed?",
    "Any issues at Reagan airport?",
    "IAD flight status",
    "Are there delays at Dulles?",
    "Is JFK airport delayed?",
    "Flight status for LaGuardia",
    "Are there delays at O'Hare?",
    "Is ATL airport open?",
    "Any delays at Atlanta airport?",
    "Flight status for Miami airport",
    "Are there delays at LAX?",
    "Is SFO airport delayed?",
    "Flight delays at Denver?",
    "Is SeaTac airport open?",
    "Any delays at Phoenix airport?",
    "Is Dallas airport delayed?",
    "Flight status for Houston",
    "Are there delays at Newark?",
    "Is Boston airport open?",
    "Any cancellations at Philadelphia?",
    "Flight delays at Charlotte?",
    "Is Orlando airport delayed?",
    "Any issues at Tampa airport?",

    # SCIENCE & TECHNOLOGY (100 questions)
    "What is quantum computing?",
    "Explain artificial intelligence",
    "How does a computer work?",
    "What is machine learning?",
    "Explain neural networks",
    "What is blockchain?",
    "How does the internet work?",
    "What is DNA?",
    "Explain photosynthesis",
    "What is gravity?",
    "How does electricity work?",
    "What is a black hole?",
    "Explain the Big Bang theory",
    "What is evolution?",
    "How do vaccines work?",
    "What is CRISPR?",
    "Explain quantum mechanics",
    "What is dark matter?",
    "How does GPS work?",
    "What is nanotechnology?",
    "Explain cloud computing",
    "What is cybersecurity?",
    "How does encryption work?",
    "What is 5G?",
    "Explain renewable energy",
    "What is solar power?",
    "How do batteries work?",
    "What is nuclear fusion?",
    "Explain climate change",
    "What causes earthquakes?",
    "How do volcanoes form?",
    "What is the water cycle?",
    "Explain the carbon cycle",
    "What is biodiversity?",
    "How does the brain work?",
    "What is memory?",
    "Explain consciousness",
    "What is sleep?",
    "How do muscles work?",
    "What is metabolism?",
    "Explain genetics",
    "What is RNA?",
    "How does cancer develop?",
    "What is immunology?",
    "Explain antibiotics",
    "What is a virus?",
    "How do bacteria work?",
    "What is a cell?",
    "Explain mitosis",
    "What is protein?",
    "How does digestion work?",
    "What is the circulatory system?",
    "Explain the nervous system",
    "What is the endocrine system?",
    "How do hormones work?",
    "What is adrenaline?",
    "Explain dopamine",
    "What is serotonin?",
    "How does vision work?",
    "What is color blindness?",
    "Explain hearing",
    "What is sound?",
    "How does light work?",
    "What is electromagnetic radiation?",
    "Explain radio waves",
    "What is WiFi?",
    "How does Bluetooth work?",
    "What is NFC?",
    "Explain RFID",
    "What is IoT?",
    "How do self-driving cars work?",
    "What is robotics?",
    "Explain automation",
    "What is 3D printing?",
    "How does virtual reality work?",
    "What is augmented reality?",
    "Explain metaverse",
    "What is cryptocurrency?",
    "How does Bitcoin work?",
    "What is Ethereum?",
    "Explain smart contracts",
    "What is NFT?",
    "How does coding work?",
    "What is Python?",
    "Explain JavaScript",
    "What is an algorithm?",
    "How do databases work?",
    "What is SQL?",
    "Explain APIs",
    "What is REST?",
    "How does GraphQL work?",
    "What is Docker?",
    "Explain Kubernetes",
    "What is DevOps?",
    "How does CI/CD work?",
    "What is Git?",
    "Explain version control",
    "What is open source?",
    "How does Linux work?",

    # HISTORY (100 questions)
    "Who was George Washington?",
    "When did World War 2 end?",
    "What caused the American Revolution?",
    "Who discovered America?",
    "When was the Declaration of Independence signed?",
    "What was the Renaissance?",
    "Who was Julius Caesar?",
    "When did the Roman Empire fall?",
    "What was the Industrial Revolution?",
    "Who was Napoleon Bonaparte?",
    "When did the Cold War end?",
    "What was the French Revolution?",
    "Who invented the telephone?",
    "When was the internet created?",
    "What was the Silk Road?",
    "Who was Genghis Khan?",
    "When did Columbus discover America?",
    "What was the Boston Tea Party?",
    "Who was Martin Luther King Jr?",
    "When did slavery end in America?",
    "What was the Great Depression?",
    "Who was Abraham Lincoln?",
    "When was the Constitution written?",
    "What was the Vietnam War?",
    "Who was Winston Churchill?",
    "When did World War 1 start?",
    "What was the Holocaust?",
    "Who was Cleopatra?",
    "When did Egypt build the pyramids?",
    "What was the Magna Carta?",
    "Who was Alexander the Great?",
    "When was Rome founded?",
    "What was the Treaty of Versailles?",
    "Who invented the printing press?",
    "When did the Middle Ages end?",
    "What was the Apollo 11 mission?",
    "Who was Neil Armstrong?",
    "When did man first land on the moon?",
    "What was the Cuban Missile Crisis?",
    "Who was JFK?",
    "When was JFK assassinated?",
    "What was the Berlin Wall?",
    "Who was Mahatma Gandhi?",
    "When did India gain independence?",
    "What was the Spanish Inquisition?",
    "Who was Leonardo da Vinci?",
    "When was the Mona Lisa painted?",
    "What was the Age of Exploration?",
    "Who was Christopher Columbus?",
    "When did the plague happen?",
    "What was the Black Death?",
    "Who was Queen Elizabeth I?",
    "When did Shakespeare live?",
    "What was the Hundred Years War?",
    "Who was Joan of Arc?",
    "When was the Battle of Waterloo?",
    "What was the Louisiana Purchase?",
    "Who was Thomas Jefferson?",
    "When was the Emancipation Proclamation?",
    "What was Pearl Harbor?",
    "Who was FDR?",
    "When did the Great Wall of China get built?",
    "What was the Ottoman Empire?",
    "Who was Attila the Hun?",
    "When did the Byzantine Empire fall?",
    "What was the Crusades?",
    "Who was King Arthur?",
    "When was Stonehenge built?",
    "What was the Viking Age?",
    "Who was Marco Polo?",
    "When did the Aztec Empire fall?",
    "What was the Inca Empire?",
    "Who was Sitting Bull?",
    "When was the Battle of Gettysburg?",
    "What was the Marshall Plan?",
    "Who was Stalin?",
    "When did the Soviet Union collapse?",
    "What was the space race?",
    "Who was Yuri Gagarin?",
    "When was Sputnik launched?",
    "What was the Manhattan Project?",
    "Who was Albert Einstein?",
    "When was the atomic bomb invented?",
    "What was D-Day?",
    "Who was Dwight Eisenhower?",
    "When did the Berlin Wall fall?",
    "What was apartheid?",
    "Who was Nelson Mandela?",
    "When did apartheid end?",
    "What was the Civil Rights Movement?",
    "Who was Rosa Parks?",
    "When was Brown v Board of Education?",
    "What was the women's suffrage movement?",
    "Who was Susan B Anthony?",
    "When did women get the right to vote?",
    "What was Prohibition?",
    "Who was Al Capone?",
    "When did Prohibition end?",

    # GEOGRAPHY (100 questions)
    "What is the capital of France?",
    "Where is Mount Everest?",
    "What is the largest ocean?",
    "Where is the Amazon rainforest?",
    "What is the longest river?",
    "Where is the Sahara desert?",
    "What is the smallest country?",
    "Where is the Great Barrier Reef?",
    "What is the largest continent?",
    "Where is the Grand Canyon?",
    "What is the deepest ocean trench?",
    "Where is Machu Picchu?",
    "What is the tallest mountain?",
    "Where is the Statue of Liberty?",
    "What is the largest country?",
    "Where is the Eiffel Tower?",
    "What is the most populous country?",
    "Where is Stonehenge?",
    "What is the capital of Japan?",
    "Where is the Taj Mahal?",
    "What is the largest desert?",
    "Where is the Colosseum?",
    "What is the capital of Australia?",
    "Where is the Golden Gate Bridge?",
    "What is the smallest continent?",
    "Where is Big Ben?",
    "What is the capital of Canada?",
    "Where is the Leaning Tower of Pisa?",
    "What is the longest mountain range?",
    "Where is the Panama Canal?",
    "What is the capital of Brazil?",
    "Where is Christ the Redeemer?",
    "What is the largest lake?",
    "Where is Niagara Falls?",
    "What is the capital of China?",
    "Where is the Great Wall of China?",
    "What is the driest place on Earth?",
    "Where is the Dead Sea?",
    "What is the capital of Egypt?",
    "Where are the pyramids of Giza?",
    "What is the wettest place on Earth?",
    "Where is the Burj Khalifa?",
    "What is the capital of India?",
    "Where is the Taj Mahal located?",
    "What is the hottest place on Earth?",
    "Where is Death Valley?",
    "What is the capital of Russia?",
    "Where is the Kremlin?",
    "What is the coldest place on Earth?",
    "Where is Antarctica?",
    "What is the capital of England?",
    "Where is Buckingham Palace?",
    "What is the largest island?",
    "Where is Iceland?",
    "What is the capital of Germany?",
    "Where is the Brandenburg Gate?",
    "What is the longest coastline?",
    "Where is the Netherlands?",
    "What is the capital of Italy?",
    "Where is the Vatican?",
    "What is the highest waterfall?",
    "Where is Angel Falls?",
    "What is the capital of Spain?",
    "Where is the Sagrada Familia?",
    "What is the largest volcano?",
    "Where is Mount Fuji?",
    "What is the capital of Mexico?",
    "Where are the Mayan ruins?",
    "What is the deepest lake?",
    "Where is Lake Baikal?",
    "What is the capital of Argentina?",
    "Where is Buenos Aires?",
    "What is the widest river?",
    "Where is the Rio de la Plata?",
    "What is the capital of South Africa?",
    "Where is Table Mountain?",
    "What is the largest bay?",
    "Where is the Bay of Bengal?",
    "What is the capital of Kenya?",
    "Where is Mount Kilimanjaro?",
    "What is the longest beach?",
    "Where is Copacabana Beach?",
    "What is the capital of Thailand?",
    "Where is the Grand Palace?",
    "What is the largest coral reef?",
    "Where is the Great Barrier Reef located?",
    "What is the capital of Indonesia?",
    "Where is Bali?",
    "What is the highest capital city?",
    "Where is La Paz?",
    "What is the capital of Peru?",
    "Where is the Amazon River?",
    "What is the most isolated island?",
    "Where is Easter Island?",
    "What is the capital of New Zealand?",
    "Where is the South Island?",
    "What is the largest gulf?",
    "Where is the Persian Gulf?",

    # MATH & LOGIC (50 questions)
    "What is 2 plus 2?",
    "What is 10 times 10?",
    "What is the square root of 144?",
    "What is 100 divided by 5?",
    "What is 50% of 200?",
    "What is the value of pi?",
    "What is 7 squared?",
    "What is the cube root of 27?",
    "What is 15 minus 8?",
    "What is 12 times 12?",
    "What is a prime number?",
    "What is the Fibonacci sequence?",
    "What is calculus?",
    "What is geometry?",
    "What is algebra?",
    "What is trigonometry?",
    "What is a right angle?",
    "What is the Pythagorean theorem?",
    "What is probability?",
    "What is statistics?",
    "What is a median?",
    "What is a mean?",
    "What is standard deviation?",
    "What is exponential growth?",
    "What is logarithm?",
    "What is a fraction?",
    "What is a decimal?",
    "What is a percentage?",
    "What is a ratio?",
    "What is a proportion?",
    "What is an integer?",
    "What is a natural number?",
    "What is a rational number?",
    "What is an irrational number?",
    "What is infinity?",
    "What is zero?",
    "What is a variable?",
    "What is an equation?",
    "What is a function?",
    "What is a derivative?",
    "What is an integral?",
    "What is a matrix?",
    "What is a vector?",
    "What is set theory?",
    "What is number theory?",
    "What is a palindrome number?",
    "What is binary?",
    "What is hexadecimal?",
    "What is Boolean logic?",
    "What is the golden ratio?",

    # COOKING & FOOD (50 questions)
    "How do you boil eggs?",
    "What is gluten?",
    "How do you make pasta?",
    "What is umami?",
    "How do you cook rice?",
    "What is yeast used for?",
    "How do you make bread?",
    "What is the difference between baking soda and baking powder?",
    "How do you cook a steak?",
    "What temperature should chicken be cooked to?",
    "How do you make scrambled eggs?",
    "What is the Maillard reaction?",
    "How do you caramelize onions?",
    "What is blanching?",
    "How do you make soup?",
    "What is a roux?",
    "How do you make gravy?",
    "What is the difference between stock and broth?",
    "How do you make pizza dough?",
    "What is proofing dough?",
    "How do you cook salmon?",
    "What is sushi?",
    "How do you make sushi rice?",
    "What is tempura?",
    "How do you make curry?",
    "What is garam masala?",
    "How do you make tacos?",
    "What is the difference between corn and flour tortillas?",
    "How do you make guacamole?",
    "What is salsa verde?",
    "How do you make marinara sauce?",
    "What is pesto?",
    "How do you cook bacon?",
    "What is the difference between bacon and pancetta?",
    "How do you make pancakes?",
    "What is buttermilk?",
    "How do you make whipped cream?",
    "What is the difference between cream and half-and-half?",
    "How do you make chocolate chip cookies?",
    "What is brown sugar?",
    "How do you make brownies?",
    "What is cocoa powder?",
    "How do you make cake?",
    "What is the difference between cake flour and all-purpose flour?",
    "How do you make frosting?",
    "What is fondant?",
    "How do you make ice cream?",
    "What is gelato?",
    "How do you make smoothies?",
    "What is the difference between juice and smoothies?",

    # HEALTH & FITNESS (50 questions)
    "How many calories should I eat?",
    "What is BMI?",
    "How much water should I drink?",
    "What is protein?",
    "How much sleep do I need?",
    "What is cardio exercise?",
    "How do you build muscle?",
    "What is stretching?",
    "How do you lose weight?",
    "What is metabolism?",
    "How many steps should I walk per day?",
    "What is a calorie?",
    "How do you do a push-up?",
    "What is a plank?",
    "How do you do squats?",
    "What is yoga?",
    "How do you meditate?",
    "What is mindfulness?",
    "How do you reduce stress?",
    "What is anxiety?",
    "How do you improve mental health?",
    "What is depression?",
    "How much exercise do I need?",
    "What is aerobic exercise?",
    "How do you improve cardiovascular health?",
    "What is blood pressure?",
    "How do you lower cholesterol?",
    "What is diabetes?",
    "How do you prevent heart disease?",
    "What is a balanced diet?",
    "How many servings of vegetables per day?",
    "What are antioxidants?",
    "How do you boost immune system?",
    "What are vitamins?",
    "How much vitamin D do I need?",
    "What is vitamin C good for?",
    "How do you prevent colds?",
    "What is the flu?",
    "How do you treat a fever?",
    "What is first aid?",
    "How do you treat a burn?",
    "What is CPR?",
    "How do you stop bleeding?",
    "What is the Heimlich maneuver?",
    "How do you treat a sprain?",
    "What is RICE treatment?",
    "How do you prevent injuries?",
    "What is proper form for exercise?",
    "How do you warm up before exercise?",
    "What is cool down after exercise?",

    # ENTERTAINMENT (100 questions)
    "Who won the Oscar for Best Picture?",
    "What is the highest-grossing movie?",
    "Who is the richest actor?",
    "What is Netflix?",
    "Who created Star Wars?",
    "What is Marvel?",
    "Who is Spider-Man?",
    "What is the MCU?",
    "Who plays Iron Man?",
    "What is Disney Plus?",
    "Who created Game of Thrones?",
    "What is HBO?",
    "Who wrote Harry Potter?",
    "What is Hogwarts?",
    "Who is Dumbledore?",
    "What is Lord of the Rings?",
    "Who is Gandalf?",
    "What is The Hobbit?",
    "Who created Star Trek?",
    "What is the Enterprise?",
    "Who is Captain Kirk?",
    "What is Doctor Who?",
    "Who is the Doctor?",
    "What is the TARDIS?",
    "Who created Breaking Bad?",
    "What is Better Call Saul?",
    "Who is Walter White?",
    "What is The Office?",
    "Who is Michael Scott?",
    "What is Friends?",
    "Who is Ross and Rachel?",
    "What is Seinfeld?",
    "Who is Jerry Seinfeld?",
    "What is The Simpsons?",
    "Who is Homer Simpson?",
    "What is Family Guy?",
    "Who is Peter Griffin?",
    "What is South Park?",
    "Who created South Park?",
    "What is Rick and Morty?",
    "Who is Rick Sanchez?",
    "What is Stranger Things?",
    "Who is Eleven?",
    "What is The Crown?",
    "Who plays Queen Elizabeth?",
    "What is The Mandalorian?",
    "Who is Baby Yoda?",
    "What is The Witcher?",
    "Who plays Geralt?",
    "What is Squid Game?",
    "Who won the Grammy?",
    "Who is Taylor Swift?",
    "What is the Super Bowl halftime show?",
    "Who is Beyonce?",
    "What is Coachella?",
    "Who is Drake?",
    "What is hip hop?",
    "Who is the Beatles?",
    "What is rock and roll?",
    "Who is Elvis Presley?",
    "What is jazz?",
    "Who is Louis Armstrong?",
    "What is classical music?",
    "Who is Mozart?",
    "What is opera?",
    "Who is Pavarotti?",
    "What is country music?",
    "Who is Johnny Cash?",
    "What is EDM?",
    "Who is Calvin Harris?",
    "What is Spotify?",
    "Who created Apple Music?",
    "What is YouTube Music?",
    "Who is the most streamed artist?",
    "What is TikTok?",
    "Who created Instagram?",
    "What is Snapchat?",
    "Who founded Facebook?",
    "What is Twitter?",
    "Who is Elon Musk?",
    "What is Reddit?",
    "Who created Reddit?",
    "What is Discord?",
    "Who uses Twitch?",
    "What is streaming?",
    "Who is PewDiePie?",
    "What is YouTube?",
    "Who created YouTube?",
    "What is a podcast?",
    "Who is Joe Rogan?",
    "What is the Joe Rogan Experience?",
    "Who is Oprah?",
    "What is the Oprah Show?",
    "Who is Jimmy Fallon?",
    "What is The Tonight Show?",
    "Who is Stephen Colbert?",
    "What is Late Night?",
    "Who is SNL?",

    # BUSINESS & FINANCE (50 questions)
    "What is a stock?",
    "How does the stock market work?",
    "What is a bond?",
    "What is compound interest?",
    "How do you invest?",
    "What is a 401k?",
    "What is an IRA?",
    "How do you save for retirement?",
    "What is diversification?",
    "What is a mutual fund?",
    "What is an ETF?",
    "What is an index fund?",
    "What is the S&P 500?",
    "What is the Dow Jones?",
    "What is NASDAQ?",
    "What is a dividend?",
    "What is a bull market?",
    "What is a bear market?",
    "What is inflation?",
    "What is deflation?",
    "What is GDP?",
    "What is unemployment rate?",
    "What is the Federal Reserve?",
    "What is monetary policy?",
    "What is fiscal policy?",
    "What is a budget?",
    "How do you make a budget?",
    "What is debt?",
    "How do you pay off debt?",
    "What is a credit score?",
    "How do you improve credit score?",
    "What is a mortgage?",
    "How do you buy a house?",
    "What is a down payment?",
    "What is interest rate?",
    "What is APR?",
    "What is a credit card?",
    "How does credit card interest work?",
    "What is bankruptcy?",
    "What is an LLC?",
    "What is a corporation?",
    "What is a startup?",
    "What is venture capital?",
    "What is an IPO?",
    "What is cryptocurrency?",
    "What is a bear market?",
    "What is supply and demand?",
    "What is market cap?",
    "What is ROI?",
    "What is profit margin?",

    # CULTURE & ARTS (100 questions)
    "Who painted the Mona Lisa?",
    "What is the Sistine Chapel?",
    "Who was Michelangelo?",
    "What is impressionism?",
    "Who was Van Gogh?",
    "What is Starry Night?",
    "Who was Picasso?",
    "What is cubism?",
    "Who was Rembrandt?",
    "What is The Night Watch?",
    "Who was Monet?",
    "What are Water Lilies?",
    "Who was Da Vinci?",
    "What is The Last Supper?",
    "Who was Raphael?",
    "What is the School of Athens?",
    "Who was Vermeer?",
    "What is Girl with a Pearl Earring?",
    "Who was Dali?",
    "What is surrealism?",
    "Who was Warhol?",
    "What is pop art?",
    "Who was Banksy?",
    "What is street art?",
    "Who wrote Romeo and Juliet?",
    "What is a sonnet?",
    "Who wrote Hamlet?",
    "What is a tragedy?",
    "Who wrote Macbeth?",
    "What is iambic pentameter?",
    "Who wrote Pride and Prejudice?",
    "What is a novel?",
    "Who wrote 1984?",
    "What is dystopia?",
    "Who wrote To Kill a Mockingbird?",
    "What is American literature?",
    "Who wrote The Great Gatsby?",
    "What is the Jazz Age?",
    "Who wrote Moby Dick?",
    "What is a classic?",
    "Who wrote War and Peace?",
    "What is Russian literature?",
    "Who wrote Crime and Punishment?",
    "What is existentialism?",
    "Who wrote The Odyssey?",
    "What is epic poetry?",
    "Who wrote The Iliad?",
    "What is Greek mythology?",
    "Who was Zeus?",
    "What is Mount Olympus?",
    "Who was Athena?",
    "What is Norse mythology?",
    "Who was Thor?",
    "What is Valhalla?",
    "Who was Odin?",
    "What is Egyptian mythology?",
    "Who was Ra?",
    "What is the Book of the Dead?",
    "Who was Anubis?",
    "What is Roman mythology?",
    "Who was Jupiter?",
    "What is the Colosseum used for?",
    "Who were gladiators?",
    "What is Buddhism?",
    "Who was Buddha?",
    "What is meditation?",
    "Who is the Dalai Lama?",
    "What is Hinduism?",
    "Who is Shiva?",
    "What is karma?",
    "Who is Vishnu?",
    "What is Islam?",
    "Who was Muhammad?",
    "What is the Quran?",
    "What is Ramadan?",
    "What is Christianity?",
    "Who was Jesus?",
    "What is the Bible?",
    "What is Easter?",
    "What is Judaism?",
    "Who was Moses?",
    "What is the Torah?",
    "What is Hanukkah?",
    "What is Taoism?",
    "Who was Lao Tzu?",
    "What is the Tao Te Ching?",
    "What is yin and yang?",
    "What is Confucianism?",
    "Who was Confucius?",
    "What is philosophy?",
    "Who was Socrates?",
    "What is the Socratic method?",
    "Who was Plato?",
    "What is The Republic?",
    "Who was Aristotle?",
    "What is logic?",
    "Who was Descartes?",
    "What is 'I think therefore I am'?",

    # HOW-TO QUESTIONS (100 questions)
    "How do you tie a tie?",
    "How do you change a tire?",
    "How do you jump start a car?",
    "How do you check oil?",
    "How do you change oil?",
    "How do you parallel park?",
    "How do you drive stick shift?",
    "How do you ride a bike?",
    "How do you swim?",
    "How do you float in water?",
    "How do you tie shoes?",
    "How do you iron a shirt?",
    "How do you do laundry?",
    "How do you remove stains?",
    "How do you sew a button?",
    "How do you use a sewing machine?",
    "How do you knit?",
    "How do you crochet?",
    "How do you paint a room?",
    "How do you hang a picture?",
    "How do you use a drill?",
    "How do you hammer a nail?",
    "How do you use a saw?",
    "How do you measure?",
    "How do you read a tape measure?",
    "How do you use a level?",
    "How do you unclog a drain?",
    "How do you fix a leaky faucet?",
    "How do you replace a toilet?",
    "How do you clean gutters?",
    "How do you mow a lawn?",
    "How do you plant a garden?",
    "How do you grow tomatoes?",
    "How do you compost?",
    "How do you prune plants?",
    "How do you water plants?",
    "How do you start a fire?",
    "How do you use a fire extinguisher?",
    "How do you pitch a tent?",
    "How do you read a compass?",
    "How do you use a map?",
    "How do you navigate?",
    "How do you purify water?",
    "How do you build a shelter?",
    "How do you tie knots?",
    "How do you fish?",
    "How do you cast a fishing rod?",
    "How do you clean a fish?",
    "How do you play guitar?",
    "How do you read music?",
    "How do you play piano?",
    "How do you sing?",
    "How do you whistle?",
    "How do you juggle?",
    "How do you do a magic trick?",
    "How do you solve a Rubik's cube?",
    "How do you play chess?",
    "How do you play poker?",
    "How do you shuffle cards?",
    "How do you throw a curveball?",
    "How do you throw a football?",
    "How do you shoot a basketball?",
    "How do you dribble?",
    "How do you serve in tennis?",
    "How do you hit a golf ball?",
    "How do you putt?",
    "How do you bowl?",
    "How do you ice skate?",
    "How do you roller skate?",
    "How do you skateboard?",
    "How do you snowboard?",
    "How do you ski?",
    "How do you surf?",
    "How do you take a photo?",
    "How do you use a camera?",
    "How do you edit photos?",
    "How do you make a video?",
    "How do you edit videos?",
    "How do you use Photoshop?",
    "How do you design a logo?",
    "How do you make a website?",
    "How do you code HTML?",
    "How do you write CSS?",
    "How do you use JavaScript?",
    "How do you create a database?",
    "How do you write SQL queries?",
    "How do you use Excel?",
    "How do you make a pivot table?",
    "How do you use PowerPoint?",
    "How do you give a presentation?",
    "How do you write a resume?",
    "How do you write a cover letter?",
    "How do you prepare for an interview?",
    "How do you negotiate salary?",
    "How do you network?",
    "How do you make small talk?",
    "How do you remember names?",
    "How do you speed read?",
    "How do you take notes?",

    # CONVERSATIONAL (70 questions)
    "How are you?",
    "What's up?",
    "How's it going?",
    "What are you doing?",
    "Tell me a joke",
    "Can you help me?",
    "What's new?",
    "Good morning",
    "Good night",
    "Thank you",
    "You're welcome",
    "What do you think?",
    "Do you agree?",
    "What's your opinion?",
    "Can you explain?",
    "Tell me more",
    "What does that mean?",
    "I don't understand",
    "Can you clarify?",
    "Say that again",
    "What did you say?",
    "Repeat that",
    "Speak louder",
    "Speak slower",
    "Go ahead",
    "Continue",
    "Keep going",
    "What else?",
    "Anything else?",
    "Is that all?",
    "Are you sure?",
    "Really?",
    "No way",
    "Seriously?",
    "You're kidding",
    "That's interesting",
    "That's cool",
    "That's amazing",
    "Wow",
    "Nice",
    "Great",
    "Awesome",
    "Fantastic",
    "Excellent",
    "Perfect",
    "Exactly",
    "Correct",
    "Right",
    "Yes",
    "No",
    "Maybe",
    "I guess",
    "Perhaps",
    "Possibly",
    "Probably",
    "Definitely",
    "Absolutely",
    "Of course",
    "Sure",
    "Okay",
    "Fine",
    "Alright",
    "Got it",
    "Understood",
    "Makes sense",
    "I see",
    "Oh",
    "Ah",
    "Hmm",
    "Tell me about yourself",
    "What can you do?",
    "Help me with something",
    "I need assistance",
    "Show me how",
    "Teach me",
    "Explain it to me",
    "Walk me through it",
    "Give me an example",
    "Can you show me?",
    "I'm confused",
]

# Verify we have 1000 questions
print(f"Total questions: {len(QUESTIONS)}")
assert len(QUESTIONS) == 1000, f"Expected 1000 questions, got {len(QUESTIONS)}"


async def test_question(client: httpx.AsyncClient, question: str, index: int) -> Dict[str, Any]:
    """Test a single question and return results."""
    start_time = time.time()

    try:
        # Use orchestrator directly to avoid HA conversation device control logic
        if USE_ORCHESTRATOR_DIRECT:
            url = f"{ORCHESTRATOR_URL}/query"
            payload = {
                "query": question,
                "session_id": f"test-1000-{index}",
                "user_id": "test-user"
            }
        else:
            url = f"{GATEWAY_URL}/ha/conversation"
            payload = {
                "text": question,
                "conversation_id": f"test-1000-{index}"
            }

        response = await client.post(
            url,
            json=payload,
            timeout=60.0  # Increased from 30s to 60s
        )

        elapsed = time.time() - start_time

        if response.status_code != 200:
            return {
                "index": index,
                "question": question,
                "success": False,
                "error": f"HTTP {response.status_code}",
                "response_time": elapsed
            }

        data = response.json()

        # Extract answer based on endpoint used
        if USE_ORCHESTRATOR_DIRECT:
            # Orchestrator /query response
            answer = data.get("answer", "")
            intent = data.get("intent")
            data_source = data.get("metadata", {}).get("data_source")
        else:
            # HA conversation response
            try:
                answer = data.get("response", {}).get("speech", {}).get("plain", {}).get("speech", "")
            except:
                answer = str(data.get("response", ""))
            intent = None
            data_source = None

        # Check if answer is helpful (not a refusal)
        unhelpful_phrases = [
            "I don't have information",
            "I don't have current information",
            "I cannot answer",
            "I'm unable to",
            "I don't know",
            "I couldn't process"
        ]

        is_helpful = len(answer) > 50 and not any(phrase in answer for phrase in unhelpful_phrases)

        return {
            "index": index,
            "question": question,
            "success": True,
            "helpful": is_helpful,
            "answer": answer,
            "answer_length": len(answer),
            "response_time": elapsed,
            "intent": intent,
            "data_source": data_source
        }

    except Exception as e:
        elapsed = time.time() - start_time
        return {
            "index": index,
            "question": question,
            "success": False,
            "error": str(e),
            "response_time": elapsed
        }


async def run_all_tests():
    """Run all 1000 questions through the system."""
    print(f"Starting 1000 question test suite...")
    print(f"Gateway URL: {GATEWAY_URL}")
    print(f"Test started at: {datetime.now().isoformat()}\n")

    results = []

    async with httpx.AsyncClient() as client:
        # Process questions SEQUENTIALLY to avoid overwhelming the system
        # Changed from batch_size=10 to batch_size=1 based on test results
        batch_size = 1  # Run one at a time to eliminate timeout issues
        for i in range(0, len(QUESTIONS), batch_size):
            batch = QUESTIONS[i:i+batch_size]
            batch_results = await asyncio.gather(
                *[test_question(client, q, idx) for idx, q in enumerate(batch, start=i+1)]
            )
            results.extend(batch_results)

            # Print progress every 10 questions
            completed = min(i + batch_size, len(QUESTIONS))
            if completed % 10 == 0 or completed == len(QUESTIONS):
                success_count = sum(1 for r in results if r["success"] and r.get("helpful", False))
                print(f"Progress: {completed}/{len(QUESTIONS)} questions | Success: {success_count}/{completed} ({success_count/completed*100:.1f}%)", flush=True)

    # Analyze results
    print("\n" + "="*80)
    print("TEST RESULTS ANALYSIS")
    print("="*80 + "\n")

    total = len(results)
    successful = sum(1 for r in results if r["success"])
    helpful = sum(1 for r in results if r.get("helpful", False))
    failed = sum(1 for r in results if not r["success"])

    success_rate = (successful / total) * 100
    helpful_rate = (helpful / total) * 100

    print(f"Total Questions: {total}")
    print(f"Successful Responses: {successful} ({success_rate:.1f}%)")
    print(f"Helpful Responses: {helpful} ({helpful_rate:.1f}%)")
    print(f"Failed Responses: {failed} ({(failed/total)*100:.1f}%)")
    print()

    # Response time stats
    response_times = [r["response_time"] for r in results if r["success"]]
    if response_times:
        avg_time = sum(response_times) / len(response_times)
        max_time = max(response_times)
        min_time = min(response_times)
        print(f"Response Time Stats:")
        print(f"  Average: {avg_time:.2f}s")
        print(f"  Min: {min_time:.2f}s")
        print(f"  Max: {max_time:.2f}s")
        print()

    # Intent distribution
    intents = {}
    for r in results:
        if r.get("intent"):
            intents[r["intent"]] = intents.get(r["intent"], 0) + 1

    if intents:
        print("Intent Distribution:")
        for intent, count in sorted(intents.items(), key=lambda x: x[1], reverse=True):
            print(f"  {intent}: {count} ({(count/total)*100:.1f}%)")
        print()

    # Data source distribution
    sources = {}
    for r in results:
        if r.get("data_source"):
            sources[r["data_source"]] = sources.get(r["data_source"], 0) + 1

    if sources:
        print("Data Source Distribution:")
        for source, count in sorted(sources.items(), key=lambda x: x[1], reverse=True):
            print(f"  {source}: {count} ({(count/total)*100:.1f}%)")
        print()

    # Sample failures
    failures = [r for r in results if not r["success"] or not r.get("helpful", False)]
    if failures:
        print(f"\nSample Failures (showing first 10 of {len(failures)}):")
        for r in failures[:10]:
            print(f"\nQ{r['index']}: {r['question']}")
            if r.get("error"):
                print(f"  Error: {r['error']}")
            elif not r.get("helpful"):
                print(f"  Unhelpful answer: {r.get('answer', '')[:100]}...")

    # Save detailed results to file
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = f"test_results_1000_{timestamp}.json"

    with open(output_file, "w") as f:
        json.dump({
            "timestamp": datetime.now().isoformat(),
            "summary": {
                "total": total,
                "successful": successful,
                "helpful": helpful,
                "failed": failed,
                "success_rate": success_rate,
                "helpful_rate": helpful_rate,
                "avg_response_time": avg_time if response_times else 0,
                "intents": intents,
                "sources": sources
            },
            "results": results
        }, f, indent=2)

    print(f"\nDetailed results saved to: {output_file}")

    # Final verdict
    print("\n" + "="*80)
    if helpful_rate >= 95:
        print("✅ SUCCESS: System achieved 95%+ helpful response rate!")
    else:
        print(f"❌ FAILURE: System achieved {helpful_rate:.1f}% helpful response rate (target: 95%)")
    print("="*80)

    return results


if __name__ == "__main__":
    asyncio.run(run_all_tests())
